export enum Sections {
    DASHBOARD = 'Dashboard',
    IAM_PERMISSIONS = 'Permissions',
    IAM_ROLES = 'Roles',
    IAM_USERS = 'Users',
    MISC_TECHNOLOGIES = 'Technologies',
    MISC_BUY_TYPES = 'Buy Types',
    MISC_BOOKING_TYPES = 'Booking Types',
    MISC_COUNTRIES = 'Countries',
    MISC_CITIES = 'Cities',
    MISC_BUYING_MODELS = 'Buying Models',
    MISC_AUDIENCES = 'Audiences',
    MISC_DEVICES = 'Devices',
    MISC_LANGUAGES = 'Languages',
    MISC_OPERATING_SYSTEMS = 'Operating Systems',
    MISC_GENDERS = 'Genders',
    MISC_CAMPAIGN_TYPES = 'Campaign Types',
    MISC_REGIONS = 'REGIONS',
}